import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        heading: ['Instrument Serif', 'serif'],
        mono: ['IBM Plex Mono', 'monospace'],
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#131313",
        foreground: "#e5e2e1",
        "secondary-fixed": "#c8c6c5",
        "outline-variant": "#474747",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "on-tertiary-container": "#000000",
        "surface": "#131313",
        "surface-tint": "#00dce5",
        "on-surface-variant": "#c6c6c6",
        "on-background": "#e5e2e1",
        "on-primary-fixed": "#ffffff",
        "primary-container": "#00ebf5",
        primary: {
          DEFAULT: "#ffffff",
          foreground: "#002021",
        },
        secondary: {
          DEFAULT: "#c8c6c5",
          foreground: "#1c1b1b",
        },
        "error-container": "#93000a",
        "inverse-on-surface": "#313030",
        outline: "#919191",
        "surface-dim": "#131313",
        "secondary-container": "#474746",
        "on-tertiary-fixed-variant": "#efdbff",
        "on-primary-container": "#000000",
        "tertiary-fixed": "#8422dc",
        tertiary: "#efdbff",
        "on-error": "#690005",
        "surface-variant": "#353534",
        "on-secondary": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#6700b5",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#63f7ff",
        "on-secondary-fixed": "#1c1b1b",
        "surface-bright": "#3a3939",
        "primary-fixed-dim": "#004f53",
        "primary-fixed": "#00696e",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#adabaa",
        "tertiary-container": "#b56eff",
        "inverse-primary": "#00696e",
        "on-secondary-container": "#e5e2e1",
        "on-primary": "#002021",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#2c0051",
        "on-tertiary-fixed": "#ffffff",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#3c3b3b",
        success: "hsl(var(--success))",
        badge: {
          organize: "hsl(var(--badge-organize))",
          "organize-text": "hsl(var(--badge-organize-text))",
          convert: "hsl(var(--badge-convert))",
          "convert-text": "hsl(var(--badge-convert-text))",
          optimize: "hsl(var(--badge-optimize))",
          "optimize-text": "hsl(var(--badge-optimize-text))",
          security: "hsl(var(--badge-security))",
          "security-text": "hsl(var(--badge-security-text))",
          edit: "hsl(var(--badge-edit))",
          "edit-text": "hsl(var(--badge-edit-text))",
        },
        offline: {
          badge: "hsl(var(--offline-badge))",
          text: "hsl(var(--offline-badge-text))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "2rem",
        md: "calc(2rem - 2px)",
        sm: "calc(2rem - 4px)",
        xl: "3rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
